# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7ad0363355106ffeb1d7dafbf5cd2fe9346a6ad58c2a0dfcd2f32d553e104f12a3101b0ee798e82529f5c8fa5e47c2bc0542edf599ed26a2fe8b541c880625ab

test:
  secret_key_base: 29f90e9796f77fecda1a93ad495dfb533716f10a8fa955b7429dbbb16ab5681596e160fed0a93eb17b4237e675ba23cc62b33e9f7c6f63959fffd8d1514d8804

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
