# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 730ac94bbdd09a714e7793fb53c9c91a3f9de9c5db380f43de95207a6a5a26f32f5016721b0aa4e69920936bea19513423401a03026849b3334aba1565047334

test:
  secret_key_base: 3324ff8fb5dfbd5e5f4ccaae4b23aa977816a9b4024fe8dce339228f3224a82bdddf20a589adfebc917c5a58eb62af497961b627eb1290fc2c98968de41c02d0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
